version: '3.4'

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.7
    container_name: zookeeper
    networks: 
      - kafka
    ports:
      - 2181:2181
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'
  kafka:
    image: docker.io/bitnami/kafka:3
    container_name: kafka
    networks: 
      - kafka
    volumes:
      - "kafka_data:/bitnami"
    ports:
      - 9092:9092
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      ALLOW_PLAINTEXT_LISTENER: 'yes' 
    depends_on:
      - zookeeper
  kafka-ui:
    image: provectuslabs/kafka-ui
    hostname: kafka-ui
    container_name: kafka-ui
    networks:
      - kafka
    depends_on:
      - zookeeper
      - kafka
    ports:
      - "8080:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
networks:
  kafka:
    driver: bridge